### ISSUE TITLE
Add customize function for formatter options, the dev is ok. when publish release version, the charts doesn't render !

### ISSUE THREAD

**Issue by lamphc** [superandrew213/react-native-charting#2]
Options：
`  let options = {
            grid: {
                top: 40,
                left: 40,
                right: 10,
                show: false
            },
            legend: {
                data: ['指标']
            },
            tooltip: {},
            xAxis: [
                {
                    boundaryGap: true,
                    type: 'category',
                    axisTick: {
                        alignWithLabel: true
                    },
                    nameTextStyle: {

                        fontSize: 10, color: '#999999'

                    },
                    //   name : '时间',
                    data: []
                }
            ],
            yAxis: [
                {
                    type: 'value',
                    min: 0,
                    max: 100

                }
            ],
            //图形的颜色组
            color: ['#1890FF'],
            //需要显示的图形名称，类型，以及数据设置
            series: [
                {
                    name: '指标',
                    //默认显
                    type: 'bar',
                    itemStyle: {
                        normal: {
                            label: {
                                show: true,
                                position: 'top',
                                textStyle: {
                                    fontSize: 10
                                },

                                formatter: '{c}'
                            }
                        },
                        emphasis: {
                            color: '#FFB131'
                        }
                    },

                    data: [],

                }
            ]
        };

        options.xAxis[0].data = ['2015', '2016', '2017']
        options.yAxis[0].max = 80
        options.series[0].data = [{ value: 10, actvalue: 10, planvalue: 100, a: 100 }, { value: 20, actvalue: 20, planvalue: 100, a: 200 }, { value: 30, actvalue: 30, planvalue: 100, a: 160 }]`

Like this, **Add customize function for formatter options**:
`
options.series[0].itemStyle.normal.label.formatter = (params) => {
            let tar = params.data
            return ((tar.actvalue / tar.planvalue).toFixed(2)) * 100 + '%'
        }
`

Compile issue？

**Comment by lamphc** [comment]
@superandrew213

**Comment by superandrew213** [comment]
Can you try this:

```
options.series[0].itemStyle.normal.label.formatter = function (params) {
  var tar = params.data;
  return ((tar.actvalue / tar.planvalue).toFixed(2)) * 100 + '%';
}
```

**Comment by lamphc** [comment]
@superandrew213  I tried using the ES5 syntax, but I still couldn't render it

**Comment by superandrew213** [comment]
@lamphc I tested this on my app and it works fine for both iOS & Android for both dev & release.

Are you having this issue on Android only? If so then you probably missed the Android extra install step:
https://github.com/superandrew213/react-native-charting#install

**Comment by superandrew213** [comment]
@lamphc I'm closing this. If you still have the issue let me know and we can reopen it.
