### ISSUE TITLE
Don't show charts.

### ISSUE THREAD

**Issue by WangJian0** [superandrew213/react-native-charting#3]
I copy echarts.html to android/app/src/main/assets. If I connect a real machine test, it's good, but when I unplug the USB and reopen the app, the charts are not displayed and a warning is posted.
WARNING:Encountered an error loading page {"canGpForward":false,"code":-6,"canGoBack":false,"description":"net::ERR_CONNECTION_REFUSED","loading":false,"title":"","url":"http://localhost:8081/assets/node_modules/react-native-charting/src/components/Echarts/echart.html?platform=android&hash=dc4f8a7558a5507ac1e4767bf5c66af3","target":5}
What should i do?

**Comment by superandrew213** [comment]
@WangJian0 this shouldn't be a problem in release build. It only happens in dev mode because the resources are loaded from the local server. Try release build.

**Comment by WangJian0** [comment]
@superandrew213  ok,i try it, thanks your help.
